# Generated by Django 5.1.4 on 2025-01-02 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('closed', 'Terminé')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('response_count', models.IntegerField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('analyzed', 'Analysé')], default='new', max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.question')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.analysis')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.theme')),
            ],
            options={
                'unique_together': {('analysis', 'theme')},
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='main_themes',
            field=models.ManyToManyField(through='surveys.AnalysisTheme', to='surveys.theme'),
        ),
        migrations.CreateModel(
            name='ResponseTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.response')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.theme')),
            ],
            options={
                'unique_together': {('response', 'theme')},
            },
        ),
    ]
